jenkins:
  systemMessage: "Configuring Jenkins automatically with JCasC plugin\n\n"
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/raphtheb/project-e.git' }
                        branch 'master'
                        extensions {}
                    }
                  }
              }
          }
      }
